spring.application.name=secureops-erp

## Server configuration
server.port=8081
server.servlet.context-path=/secureops

# Error handling
server.error.include-message=always

# Database configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/secureops_db
spring.datasource.username=postgres
spring.datasource.password=Yasser@256
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Logging configuration
logging.level.org.springframework=INFO
logging.level.com.secureops=DEBUG
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

# Security Configuration
spring.security.user.name=admin
spring.security.user.password=admin

# Jackson Configuration
spring.jackson.date-format=yyyy-MM-dd HH:mm:ss
spring.jackson.time-zone=UTC
spring.jackson.serialization.write-dates-as-timestamps=false

# Application-specific properties
app.quote.number.format=SO%05d
app.order.number.format=OR%05d
app.invoice.number.format=INV%05d
